### ISSUE TITLE
Milestone 1 - Unit 10: Deadline April 18th

### ISSUE THREAD

**Issue by Alytraore** [cassiopeia0329/Cassiopeia#1]

**Comment by blinkous** [comment]
- [ ] Create the parse/firebase server
- [ ] Create the UI
- [ ] Add the networking calls
