### ISSUE TITLE
Milestone 4 - Unit 13: Deadline May 3rd

### ISSUE THREAD

**Issue by Alytraore** [cassiopeia0329/Cassiopeia#4]

**Comment by blinkous** [comment]
- [ ] Create UI to change profile
- [ ] Update the server with changes
- [ ] Update the profile
